<a href="https://colab.research.google.com/github/joaozalina/PyTorch---fundamentals/blob/main/00_pytorch_fundamentals_video.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. Pytorch Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

If you have a questions: https://github.com/mrdbourke/pytorch-deep-learning/discussions

## Libraries

In [ ]:
'''
The code below shows the libraries we're using for this PyTorch project.

Obs: print(torch.__version__) = shows the PyTorch's version.

'''
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.9.0+cu126


### PyTorch CODE - Introduction to *TENSORS*

Creating tensors

In [ ]:
print("Hello! I'm excited to learn PyTorch!")

Hello! I'm excited to learn PyTorch!


PyTorch tensors are created using `torch.Tensor()` = https://docs.pytorch.org/docs/stable/tensors.html

In [ ]:
# 1 Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
'''
Scalar's tensors don't have dimentions.
'''
scalar.ndim

0

In [ ]:
# Get tensor back as Python int
'''
It returned number 7 that we set in the tensor's expression above.
'''
scalar.item()

7

In [ ]:
# Vector

vector = torch.tensor([7, 7])
vector


tensor([7, 7])

In [ ]:
'''
Vector's tensors have one (01) dimention.

Dimentions is like the "number of pairs square brackets []" a tensor have.

EX: ([]) = 1 Pair of square brackets = 1 Dimention.
'''
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
'''

'''
MATRIX = torch.tensor([[7, 8],
                      [9, 10]]
                      )
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
'''
Matrix's tensors have two (02) dimentions - 2 pairs of square brackets [].
'''
MATRIX.ndim

2

In [ ]:
'''
Verifying the 'MATRIX's indexes

'''

print(MATRIX[0]) #Will return [7 , 8]

print(MATRIX[1]) #Will return [9 , 10]

tensor([7, 8])
tensor([ 9, 10])


In [ ]:
'''
We will get '[2, 2]' because in MATRIX we have 2 rows and 2 columns - 2 numbers and 2 pairs of square brackets [].
'''
MATRIX.shape

torch.Size([2, 2])

In [ ]:
#Tensor

TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR


tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
'''
Tensor's have three (03) dimentions - 3 pairs of square brackets [].
'''
TENSOR.ndim

3

In [ ]:
# Tensor shape
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [ ]:
# The 'JoTensor' is just for me to understand better how does "shapes work."
JoTensor = torch.tensor([[[[[1, 2, 3, 4, 5],
                           [6, 7, 8, 9, 10],
                           [11, 12, 13, 14, 15],
                           [16, 17, 18, 19, 20]
                           ]]]])
JoTensor.shape

torch.Size([1, 1, 1, 4, 5])

In [ ]:
# Number of dimentions 'JoTensor' have.

'''
The 'JoTensor' has 5(five) dimentions because we have:

- 1(one) dimention for all the numbers in the group of "blue square brackets".

- 1(one) consecutive dimention (total is 4) for each square bracket AFTER or BEFORE THE GROUP OF "BLUE SQUARE BRACKETS".


So: 1 (Blue group of square brackets) + 4 (consecutive dimentions after or before the blue group of square brackets) = 5 dimentions

'''


JoTensor.ndim

5

We will tipically see `scalar` and `vector` in LOWER CASE and `MATRIX` and `TENSOR` in UPPER CASE. It's just "how developers around the world write these variables."

## Random tensors

Why random tensors?

Random tensors are important because the way many **NEURAL NETWORKS LEARN** is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

` Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

"It's likely the neural networks work flow."

Torch random tensors: https://docs.pytorch.org/docs/stable/random.html#module-torch.random

**___**

In [ ]:
# Create a random tensor of size (3, 4)

random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.1534, 0.9982, 0.2913, 0.5024],
        [0.7782, 0.2942, 0.4703, 0.8195],
        [0.7416, 0.6702, 0.2582, 0.3220]])

In [ ]:
# Numbers of dimentions of "random_tensor".

'''
It has 2 dimentions.
'''

random_tensor.ndim

2

In [ ]:
# Create a random tensor with similar shape to an image tensor

random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height(224), width(224), color channels(3) (R, G, B).   OBS: Sometimes color channels can appears first then height & width.

random_image_size_tensor.shape, random_image_size_tensor.ndim


(torch.Size([224, 224, 3]), 3)

## Zeros and Ones (They're kind of tensors)

In [ ]:
# Create a tensor of all zeros

zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# zeros(variable) x random_tensor(variable)

'''

Maybe when working with a "random_tensor", we'd like to hide/mask the numbers of
the column. For this, we can create a "tensor of zeros (torch.zeros(size=3,4))",
and multiply it by the 'random_tensor' we created.

What will happen is that the random numbers inside of a "random_tensor" will be-
come masked.
'''

zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Create a tensor of all ones

ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
# Verifying the data type

ones.dtype

torch.float32

In [ ]:
# Our 'random_tensor' is also a float because...

random_tensor.dtype

torch.float32

## Creating a **range** of tensors and tensors-like

In [ ]:
# torch.range()

'''
UserWarning: torch.range is deprecated and will be removed in a future release
because its behavior is inconsistent with Python's range builtin. Instead, use
torch.arange, which produces values in [start, end]).
'''

torch.range(0, 10)

/tmp/ipython-input-3345247799.py:9: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0, 10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

### As long as 'torch.range' will be deprecated, we need to use `torch.arange()` to create "range functions".

torch.arange documentation: https://docs.pytorch.org/docs/stable/generated/torch.arange.html#torch.arange

In [ ]:
# torch.arange()

'''
The parameter 'step' is optional and 1 by default. For the expression below, if
we set the 'step = 2', as we created an arange from 1 to 10, the output will be:

[2, 4, 6, 8, 10]

Instead of:

[1,  2,  3,  4,  5,  6,  7,  8,  9, 10]
'''


one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Creating **tensors like**

In [ ]:
'''
Let's supose that we have a particular "shape of a tensor and you want to repli-
cate it in somewher else, but you didn't want to specifically define what that
shape should be...
'''

'''

Well, if we want to create a tensor full of 'zeros' with the same shape as
'one_to_ten' (our previous variable) we can use "TENSORS LIKE":

torch.zeros_like(input=one_to_ten)

'''

ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensors ***Data Types*** (important topic!)

In [ ]:
# Float 32 tensor

float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,
                               device=None,
                               requires_grad=False)

float_32_tensor

tensor([3., 6., 9.])

In [ ]:
# Checking the data type of 'float_32_tensor'

float_32_tensor.dtype

torch.float32

When checking the data type of 'float_32_tensor' (variable created), we can see that the output was "a float data type (torch.float32)" even we setting as parameter (dtype=none). So why we got an output of "float data type"? This is because the **defaut data type in PyTorch**, even if specified as "**none**", is going to come out as "float32". Now what is "float32"?

**Float32** is is a kind of data type **for PyTorch**. As developers, we have seen data types as: **int**, **float**, **boolean**, **double**, **string**, **object** and etc. Unlike the ones I've just mentioned, the "**float32**", as well "**float64**", "**float16**", "**complex128**" is a kind of data type for PyTorch.

The most common ones we might find are "float32" and "float16". But what are the **128**, **64**, **32**, **16** and etc from this kind of data type? They have to do with "**PRECISION IN COMPUTING.**" The **higher the "number bit"** ***the higher will be detail and the space occupied in memory***. It will also take more time for "processing".

*   Half precision is: 16 bit
*   Single precision is: 32 bit
*   "More precision is": 64-bit



We can get more information about "precision in coputing" here: https://en.wikipedia.org/wiki/Precision_(computer_science)

Everything is worthing reading, but what might be important for us is the "Single-precision floating-point" format: https://en.wikipedia.org/wiki/Single-precision_floating-point_format

We can get more information about PyTorch data type here: https://docs.pytorch.org/docs/stable/tensor_attributes.html#dtype-doc

Tensors datatypes is **one of the 3 big errors** you'll run into **PyTorch** & **Deep Learning:**



1.   Tensors not right **datatype**
2.   Tensors not right **shape**
3.   Tensors not on the **right device**




In [ ]:
# Also the parameters:

'''
The parameters:

- dtype = None
- device = None
- requires_grad = False

They're the three of the most important parameters when we're creating TENSORS.
"We always have to use" these parameters as: dtype=None, device=None and
requires_grad=False because PyTorch does A LOT OF tensors creations "behind the
scenes."

THIS IS VERY IMPORTANT!
'''

#Example using this code from earlier. Pay attention for the parameters
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,
                               device=None,
                               requires_grad=False)

Let's supose we run into a "tensor data type error" while doing some calculations. For example:

We have a variable 'tensor_64" (with the value of 64 bit) and we, for some reason, have to convert it in another "tensor data type" in order to do the calculations ***without having a error***.

What we can do is convert the 'tensor's variable' for a value that matches the one we're going to do the calculation/expression. Example:


*   float_16_tensor = float_64_tensor.type(**torch.float16**)

## Getting information from tensors (**Tensor attributes**)

1.   Tensors not right datatype - to do for get datatype from a tensor, can use `tensor.dtype`
2.   Tensors not right shape - to do for get shape from a tensor, can use `tensor.shape`
3.   Tensors not on the right device - to do for get the device from a tensor, can use `tensor.device`

In [ ]:
# Creation of tensors for the examples above

some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.9782, 0.5094, 0.1910, 0.5658],
        [0.0245, 0.6792, 0.9550, 0.5479],
        [0.0412, 0.9475, 0.1270, 0.3329]])

In [ ]:
# Find out details about "some_tensor"

print(some_tensor)

print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Devive tensor is on: {some_tensor.device}")

tensor([[0.9782, 0.5094, 0.1910, 0.5658],
        [0.0245, 0.6792, 0.9550, 0.5479],
        [0.0412, 0.9475, 0.1270, 0.3329]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Devive tensor is on: cpu


In [ ]:
# KEEP FROM CLASS 26 from PyTorch